name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-13
          - windows-latest
        node-version:
          - 12
          - 14
          - 15
          - 16
          - 17
          - 18
          - 19
          - 20
          - 21
          - 22
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci --ignore-scripts
      - name: Run Tests
        run: npm test

  license-lint:
    name: License Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
  
      - name: Set up Python (for reuse tool dependencies)
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
  
      - name: Install reuse
        run: pip install reuse
  
      - name: Run REUSE compliance check
        run: reuse lint
